[project]
name = "researcher-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai-tools>=0.71.0",
    "crewai[tools]>=0.186.1",
    "docling>=2.61.1",
    "pymupdf>=1.26.6",
]
